---
- name: Create directory for discourse
  file:
    path: /var/discourse
    state: directory

- name: Clone the Discourse Docker Git Repo
  git:
    repo: 'https://github.com/discourse/discourse_docker.git'
    dest: /var/discourse
    version: 755fff3554efadca975e5d7a6db3da135dd039e4

- name: Create Discourse app.yml config file
  template:
    src: app.yml.j2
    dest: /var/discourse/containers/app.yml
    force: yes
    owner: root
    group: root

- name: Execute Discourse bootstrap
  command:  ./launcher rebuild app
  args:
    chdir: /var/discourse

