---
apiVersion: v1
kind: Service
metadata:
  name: rook-external
  namespace: rook
  labels:
    app: rgw
    rook_cluster: rook
spec:
  ports:
  - name: rgw
    port: 53390
    protocol: TCP
    targetPort: 53390
  selector:
    app: rgw
    rook_cluster: rook
  sessionAffinity: None
  type: NodePort
