engines:
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      config: "code/datalab-app/.eslintrc"
    checks:
      import/no-unresolved:
        enabled: false
      import/extensions:
        enabled: false
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 45
  markdownlint:
    enabled: true
ratings:
  paths:
  - "code/datalab-app/**"
  - "code/dynamic-proxy/**"
  - "**.md"
exclude_paths:
- "code/provision/**/*"
- "docs/styles/website.css"
- "**/node_modules/**"
