sudo: required

before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

language: node_js

node_js: 6

services: docker

cache:
  yarn: true
  directories: node_modules

script:
  - cd $TRAVIS_BUILD_DIR/code/datalab-app/ && yarn install && yarn test && yarn lint

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      yarn global add gitbook-cli;
      cd $TRAVIS_BUILD_DIR/code/datalab-app/ && yarn build && docker build -f app.Dockerfile -t nerc/datalab-app . && docker build -f api.Dockerfile -t nerc/datalab-api .;
      cd $TRAVIS_BUILD_DIR/docs/ && gitbook build && docker build -t nerc/docs .;
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push nerc/datalab-app && docker push nerc/datalab-api && docker push nerc/docs;
    fi

notifications:
  email: false
  slack:
    secure: MOXMAAY0fBeiwXodgXeBaZO39500l4Fg53GxMoLOXipoPUckTSvsg21fb8nYr2FeEKSlF/6g/IAoH9WCthnhFxLKGo+HLNkoSlV9CIz69v6YdjgEaM5o68D5Pg2mQ10xxbtGYICUh7U7Cq2xhQK+hT+wsEeeuiCWmdBKc3J30KHt7PPJ1tCx98gUv8QxRQfhSUAjbLzjap6Y4qKfsdwRVRnv44D4qQ8kc9YOSbzAo0b7A969T0RPR9N/WlB39mCzOn4yqVpzyF5xQsxAjPJuYgYBUkPbK505SLrm7jP18wMlD2qEhfVikSVTDVSmxZB86msn2YpQoGrrdQWMp+520PXrkGilD7z2BItQq93CzplIJ5NlfA9TF2p5A3uWRwTobxB5ErjQ0iCl0zs+2/v422cTnaufqwQBQ7W/4y9CJb8f3DpUStjU5W4CK1cRnx6vqSi34usy6NxrVNf6NbmobFMOCuTe8ChYpzBYgGXuvNw4vUz1APRkr6mcOKI4kRaG05WBdrS2MiTROffrHt1AvQPJ5ZHJcf+T4p4k8C31rDif3Zd6xcN4yPYpLX5Ly8O0K9/IEXurVdNiRTMGhvOeFKBMtmcSFkM3L2tmwEqtveoRO/JvGc+AAHf35ALSNG0ZOC79tI0tCxyG3FP3j9VEix6d5EjaaeRFvhnncODI0aU=
