---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: kube-system
  name: glusterfs-storage
provisioner: docker.io/hostpath
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: kube-system
  name: nfs-storage
provisioner: docker.io/hostpath
