---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: datalab-app-ingress
  namespace: devtest
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - testlab.datalabs.localhost
    secretName: tls-secret
  rules:
  - host: testlab.datalabs.localhost
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: datalab-api-proxy
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: datalab-app-proxy
            port:
              number: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: datalab-api-proxy
  namespace: devtest
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: datalab-api-proxy
  namespace: devtest
subsets:
- addresses:
  - ip: 192.168.91.128
  ports:
  - name: app
    port: 8000
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: datalab-app-proxy
  namespace: devtest
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: datalab-app-proxy
  namespace: devtest
subsets:
- addresses:
  - ip: 192.168.91.128
  ports:
  - name: app
    port: 3000

