---
kind: Service
apiVersion: v1
metadata:
  name: datalab-app-proxy
  namespace: devtest
spec:
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ExternalName
  externalName: 192.168.0.61
---
kind: Service
apiVersion: v1
metadata:
  name: datalab-api-proxy
  namespace: devtest
spec:
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ExternalName
  externalName: 192.168.0.61
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: datalab-app-ingress
  namespace: devtest
spec:
  tls:
  - hosts:
    - testlab.datalabs.localhost
    secretName: tls-secret
  rules:
  - host: testlab.datalabs.localhost
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: datalab-api-proxy
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: datalab-app-proxy
            port:
              number: 3000
