---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-claim
  namespace: devtest
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testlab-internal-claim
  namespace: devtest
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

