- name: Copy Helm Chart to k8s-master
  copy:
    src: files/
    dest: "{{ chart_directory }}"
    owner: ubuntu
    group: docker
    mode: 0644

- name: Create values file from template
  template:
    src: values.yml.j2
    dest: "{{ chart_directory }}/values.yml"
    force: yes
    owner: "{{ deploy_user }}"
    group: docker

- name: Install chart
  command: "helm upgrade --install {{ namespace.name }}-discourse-svc --namespace {{ namespace.name }} --tls -f {{ chart_directory}}/values.yml {{ chart_directory }}"

- name: Delete temporary helm chart directory
  file: path={{ tmp_directory }} state=absent