---
- name: Get the Host Keys
  shell: "ssh-keyscan -H -T 10 -t ecdsa-sha2-nistp256 {{ hostvars[item].openstack.private_v4 }}"
  with_items: "{{ groups[server_group] }}"
  register: ssh_known_host_results
  ignore_errors: yes

- name: Create known_hosts file
  file:
    path: "/home/{{ deploy_user }}/.ssh/known_hosts"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    state: touch

- name: Add hosts to /home/ubuntu/.ssh/known_hosts
  blockinfile:
    path: "/home/{{ deploy_user }}/.ssh/known_hosts"
    block: "{{ item.stdout }}"
    marker: "# {mark} ANSIBLE MANAGED HOST ENTRY {{ item.item }}"
  with_items: "{{ ssh_known_host_results.results }}"
