apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: jupyter-notebook
  name: jupyter-notebook
spec:
  template:
    metadata:
      labels:
        name: jupyter-notebook
    spec:
      containers:
      - image: jupyter/base-notebook:b4dd11e16ae4
        imagePullPolicy : "IfNotPresent"
        name: jupyter-notebook
        command: ["start-notebook.sh", "--NotebookApp.token='$(JUPYTER_TOKEN)'"]
        ports:
        - containerPort: 8888
          protocol: TCP
        env:
        - name: JUPYTER_TOKEN
          valueFrom:
            secretKeyRef:
              name: jupyter-secret
              key: token
        volumeMounts:
            - mountPath: /data
              name: glusterfsvol
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 2
            memory: 4Gi
      volumes:
        - name: glusterfsvol
          glusterfs:
            endpoints: glusterfs-cluster
            path: datalab
            readOnly: false
---
kind: Service
apiVersion: v1
metadata:
  name: jupyter-notebook-service
spec:
  ports:
    - name: jupyter-notebook-web-ui
      port: 80
      targetPort: 8888
  selector:
    name: jupyter-notebook
  type: NodePort
