apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.datalabName }}-internal-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: glusterfs-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.internalVolumeSize }}
