## Additional command line arguments to pass to nginx-ingress-controller
## E.g. to specify the default SSL certificate you can use
## extraArgs:
##   default-ssl-certificate: "<namespace>/<secret_name>"
controller:
  extraArgs:
    default-ssl-certificate: devtest/tls-secret
