---
- name: Create temporary helm chart directory
  file: path={{ chart_directory }} state=directory

- name: Create values file from template
  template:
    src: values.yml.j2
    dest: "{{ chart_directory }}/values.yml"
    force: yes

- name: Install chart
  command: "helm upgrade --tls --install nginx-ingress-controller stable/nginx-ingress --version {{ helm_nginx_version }} --namespace kube-system -f {{ chart_directory }}/values.yml --debug"

- name: Delete temporary helm chart directory
  file: path={{ tmp_directory }} state=absent
