---
- name: Install Nginx Ingress Helm Chart
  hosts: k8s-master

  roles:
    - role: kubernetes-namespace
      namespace: "{{ test_namespace }}"
    - role: kubernetes-secrets

  environment:
    HELM_HOME: "/home/{{ deploy_user }}/helm"
  tags:
    - config
