---
- hosts: new
  user: root
  gather_facts: False

  roles:
    - secure-server

- hosts: new
  user: "{{ deploy_user }}"
  become: yes
  become_method: sudo

  roles:
    - setup-networking
    - base-configuration
