---
- name: Prepare all rke cluster nodes
  hosts: rke-k8s-cluster
  become: yes
  become_method: sudo

  roles:
    - docker
    - { role: glusterfs, gluster_server: False }
    - app-armor
    - rke-kubernetes-common
    - rke-kubernetes

- name: Configure Helm
  hosts: cehsos-k8s-master-3

  roles:
    - helm
  environment:
    HELM_HOME: "/home/{{ deploy_user }}/helm"


- name: Install Nginx Ingress Helm Chart
  hosts: cehsos-k8s-master-3

  roles:
    - role: ingress-controller
      namespace: "{{ prod_namespace }}"
    - role: kubernetes-secrets

  environment:
    HELM_HOME: "/home/{{ deploy_user }}/helm"
  tags:
    - config


- name: Initialize DataLabs
  hosts: cehsos-k8s-master-3

  roles:
    - role: datalabs-base
      datalab: "{{ test_namespace }}"
    - role: datalabs-base
      datalab: "{{ prod_namespace }}"
    #- role: vault-secrets
    #  datalab: "{{ test_namespace }}"
    #- role: vault-secrets
    #  datalab: "{{ prod_namespace }}"

  environment:
    HELM_HOME: "/home/ubuntu/helm"