- hosts: discourse
  user: "{{ deploy_user }}"
  become: yes
  become_method: sudo

  roles:
    - docker
    - discourse

- name: Discourse service configuration
  hosts: k8s-master

  roles:
    #- role: discourse-k8s-service
    #  namespace: "{{ test_namespace }}"
    #  discourseHost: "{{ groups['test-discourse'][0] }}"
    - role: discourse-k8s-service
      namespace: "{{ prod_namespace }}"
      discourseHost: "{{ groups['prod-discourse'][0] }}"

  environment:
    KUBECONFIG: "/home/{{ deploy_user }}/admin.conf"
    HELM_HOME: "/home/ubuntu/helm"
  tags:
    - config