---
# The ID of the APT key for the Kubernetes repository
kubernetes_apt_key_id: 6A030B21BA07F4FB

kubernetes_packages:
  - jq=1.5+dfsg-1ubuntu0.1
  - kubelet=1.10.11-00
  - kubeadm=1.10.11-00
  - kubectl=1.10.11-00
  - kubernetes-cni=0.6.0-00
