apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{name}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{scaleDeploymentName}}
  minReplicas: 1
  maxReplicas: {{maxReplicas}}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{targetCpuUtilization}}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{targetMemoryUtilization}}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{scaleDownWindowSec}}
