apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{name}}
spec:
  podSelector:
    matchLabels:
      spark-infra: {{schedulerPodLabel}}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{projectKey}}
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 7077
