apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{networkPolicyName}}
spec:
  podSelector:
    matchLabels:
      dask-infra: scheduler-{{name}}-po
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{projectKey}}
    ports:
    - protocol: TCP
      port: 8786
    - protocol: TCP
      port: 8787
