apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      spark-infra: {{schedulerPodLabel}}
  template:
    metadata:
      labels:
        spark-infra: {{schedulerPodLabel}}
        name: {{ clusterName }}
        user-pod: {{ type }}
    spec:
      containers:
        - image: {{{sparkImage}}}
          name: {{schedulerContainerName}}
          env:
            - name: SPARK_MODE
              value: "master"
          ports:
            - containerPort: 8080
            - containerPort: 7077
          resources:
            requests:
              memory: {{schedulerMemory}}
              cpu: {{schedulerCpu}}
            limits:
              memory: {{schedulerMemory}}
              cpu: {{schedulerCpu}}
          volumeMounts:
            {{#volumeMount}}
            - name: persistentfsvol
              mountPath: /data
            {{/volumeMount}}
      hostname: spark-scheduler-host
      restartPolicy: Always
      volumes:
        {{#volumeMount}}
        - name: persistentfsvol
          persistentVolumeClaim:
            claimName: {{ volumeMount }}-claim
        {{/volumeMount}}
