apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{autoScalerName}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{workerDeploymentName}}
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{workerCpuUtilization}}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{workerMemoryUtilization}}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{workerScaleDownWindowSec}}
