apiVersion: v1
kind: Service
metadata:
  name: scheduler-{{name}}-svc
spec:
  ports:
    - name: "client"
      port: 8786
      targetPort: 8786
    - name: "dashboard"
      port: 8787
      targetPort: 8787
  selector:
    dask-infra: scheduler-{{name}}-po
