apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      spark-infra: {{workerPodLabel}}
  template:
    metadata:
      labels:
        spark-infra: {{workerPodLabel}}
    spec:
      containers:
        - image: {{{sparkImage}}}
          name: {{workerContainerName}}
          env:
            - name: SPARK_MODE
              value: "worker"
            - name: SPARK_MASTER_URL
              value: "spark://{{schedulerServiceName}}:7077"
          resources:
            requests:
              memory: {{workerMemory}}
              cpu: {{workerCpu}}
            limits:
              memory: {{workerMemory}}
              cpu: {{workerCpu}}
          volumeMounts:
            {{#volumeMount}}
            - name: persistentfsvol
              mountPath: /data
            {{/volumeMount}}
      hostname: spark-worker-host
      restartPolicy: Always
      volumes:
        {{#volumeMount}}
        - name: persistentfsvol
          persistentVolumeClaim:
            claimName: {{ volumeMount }}-claim
        {{/volumeMount}}
