apiVersion: v1
kind: Service
metadata:
  name: {{name}}
spec:
  ports:
    - name: "client"
      port: 8080
      targetPort: 8080
    - name: "driver"
      port: 7077
      targetPort: 7077
  selector:
    spark-infra: {{schedulerPodLabel}}
