apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-{{name}}-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      dask-infra: worker-{{name}}-po
  template:
    metadata:
      labels:
        dask-infra: worker-{{name}}-po
    spec:
      containers:
        - image: {{{daskImage}}}
          command: ["bash"]
          args: ["-c", "{{{workerPath}}} --nthreads {{nThreads}} --no-dashboard --memory-limit {{workerMemory}} --death-timeout {{deathTimeoutSec}} tcp://scheduler-{{name}}-svc:8786"]
          name: dask-worker-cont
          resources:
            requests:
              memory: {{workerMemory}}
              cpu: {{workerCpu}}
            limits:
              memory: {{workerMemory}}
              cpu: {{workerCpu}}
          volumeMounts:
            {{#volumeMount}}
            - name: persistentfsvol
              mountPath: /data
            {{/volumeMount}}
      hostname: dask-worker-host
      restartPolicy: Always
      volumes:
        {{#volumeMount}}
        - name: persistentfsvol
          persistentVolumeClaim:
            claimName: {{ volumeMount }}-claim
        {{/volumeMount}}
