apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      dask-infra: {{schedulerPodLabel}}
  template:
    metadata:
      labels:
        dask-infra: {{schedulerPodLabel}}
    spec:
      containers:
        - image: {{{daskImage}}}
          command: ["bash"]
          args: ["-c", "{{{schedulerPath}}}"]
          name: dask-scheduler-cont
          ports:
            - containerPort: 8786
            - containerPort: 8787
          resources:
            requests:
              memory: {{schedulerMemory}}
              cpu: {{schedulerCpu}}
            limits:
              memory: {{schedulerMemory}}
              cpu: {{schedulerCpu}}
          volumeMounts:
            {{#volumeMount}}
            - name: persistentfsvol
              mountPath: /data
            {{/volumeMount}}
      hostname: dask-scheduler-host
      restartPolicy: Always
      volumes:
        {{#volumeMount}}
        - name: persistentfsvol
          persistentVolumeClaim:
            claimName: {{ volumeMount }}-claim
        {{/volumeMount}}
