---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ name }}
  annotations:
{{#privateEndpoint}}
    nginx.ingress.kubernetes.io/auth-url: {{ &authServiceUrl }}
{{/privateEndpoint}}
    nginx.ingress.kubernetes.io/auth-signin: {{ &authSigninUrl }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ &maxBodySize }}
{{#rewriteTarget}}
    nginx.ingress.kubernetes.io/rewrite-target: {{ &rewriteTarget }}
{{/rewriteTarget}}
{{#proxyRequestBuffering}}
    nginx.ingress.kubernetes.io/proxy-request-buffering: "{{ &proxyRequestBuffering }}"
{{/proxyRequestBuffering}}
{{#proxyTimeout}}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "{{ &proxyTimeout }}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{ &proxyTimeout }}"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "{{ &proxyTimeout }}"
    nginx.ingress.kubernetes.io/proxy-socket-keepalive: "on"
{{/proxyTimeout}}
{{#proxyHeadersConfigMap}}
    nginx.ingress.kubernetes.io/proxy-set-headers: "{{ &proxyHeadersConfigMap }}"
{{/proxyHeadersConfigMap}}
{{#clusterIssuer}}
    cert-manager.io/cluster-issuer: "{{ &clusterIssuer }}"
{{/clusterIssuer}}
spec:
  tls:
  - hosts:
    - {{ service.host }}
    {{#clusterIssuer}}
    secretName: "{{ name }}-tls-secret"
    {{/clusterIssuer}}
  rules:
  - host: {{ service.host }}
    http:
      paths:
{{#service.paths}}
      - path: {{ &path }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ serviceName }}
            port:
              number: {{ servicePort }}
{{/service.paths}}
