---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ name }}
data:
  spark-kubernetes.properties: |
    spark.driver.host={{ name }}-headless.prod.svc.cluster.local
    spark.driver.port=29413
    spark.executor.instances=4
    spark.executor.memory=4g
    spark.kubernetes.authenticate.caCertFile=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    spark.kubernetes.authenticate.oauthTokenFile=/var/run/secrets/kubernetes.io/serviceaccount/token
    spark.kubernetes.container.image=gcr.io/spark-operator/spark-py:v2.4.0
    spark.kubernetes.executor.limit.cores=2
    spark.kubernetes.executor.request.cores=0.5
    spark.kubernetes.namespace={{ project-compute-namespace }}
    spark.kubernetes.pyspark.pythonVersion=3
    spark.master=k8s://https://kubernetes.default.svc.cluster.local:443
    spark.submit.deployMode=client
    spark.app.name={{ name }}-spark-job
