---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: {{ name }}
  name: {{ name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ name }}
  template:
    metadata:
      labels:
        name: {{ name }}
        user-pod: {{ type }}
    spec:
      initContainers:
        # This container will correct the directory permissions for the dynamically provisioned storage. Without this it
        # is not possible to write to the mounted directory.
        - name: fix-permissions
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sh"]
          args: ["-c", "chmod 777 /mnt/glusterfs"]
          volumeMounts:
            - mountPath: /mnt/glusterfs
              name: glusterfsvol
      containers:
        - name: minio
          image: {{ &minio.imageName }}:{{ minio.version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
              protocol: TCP
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ name }}
                  key: access_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ name }}
                  key: secret_key
          args: ["server", "/mnt/glusterfs"]
          volumeMounts:
            - mountPath: /mnt/glusterfs
              name: glusterfsvol
          livenessProbe:
            httpGet:
              path: /minio/login
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
        - name: {{ name }}-connect
          image: {{ &minio.connectImageName }}:{{ minio.connectVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ORIGIN
              value: {{ domain }}
            - name: ACTIONS
              value: "['set']"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: glusterfsvol
          persistentVolumeClaim:
            claimName: {{ volumeName }}-claim
