---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: {{ name }}
  name: {{ name }}
spec:
  selector:
    matchLabels:
      name: {{ name }}
  template:
    metadata:
      labels:
        name: {{ name }}
        user-pod: {{ type }}
    spec:
      # No init container need as the subPath variable only mounts the required directory. If the directory is missing
      # this is automatically created.
      containers:
        - name: {{ name }}
          image: {{ &image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5006
              protocol: TCP
          command: ["sh"]
          args: ["-c",
            "cd /notebooks && panel serve . --show"]
          livenessProbe:
            httpGet:
              path: /
              port: 5006
            initialDelaySeconds: 5
            periodSeconds: 10
{{#volumeMount}}
          volumeMounts:
            - name: persistentfsvol
              mountPath: /notebooks
              subPath: {{ &sourcePath }}
              readOnly: true
      volumes:
        - name: persistentfsvol
          persistentVolumeClaim:
            claimName: {{ volumeMount }}-claim
{{/volumeMount}}
