---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: {{ name }}
  name: {{ name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ name }}
  template:
    metadata:
      labels:
        name: {{ name }}
        user-pod: {{ type }}
    spec:
      containers:
        - image: {{ &rshiny.imageName }}:{{ rshiny.version }}
          imagePullPolicy: "IfNotPresent"
          name: {{ name }}
          ports:
            - containerPort: 3838
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 1
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /
              port: 3838
            initialDelaySeconds: 5
            periodSeconds: 10
{{#volumeMount}}
          volumeMounts:
            - name: glusterfsvol
              mountPath: /data
              readOnly: true
            - name: glusterfsvol
              mountPath: /srv/shiny-server
              subPath: {{ &sourcePath }}
      volumes:
        - name: glusterfsvol
          persistentVolumeClaim:
            claimName: {{ volumeMount }}-claim
{{/volumeMount}}
