---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: {{ name }}
  name: {{ name }}
spec:
  selector:
    matchLabels:
      name: {{ name }}
  template:
    metadata:
      labels:
        name: {{ name }}
        user-pod: {{ type }}
    spec:
      initContainers:
        # This container will generate the RStudio notebooks directory. RStudio starts with /home/datalabs as its initial
        # start-up/default directory and has not environmental variable to change it. This is fixed by mounting an empty
        # directory as /home and created a symlink datalabs pointing to /data/notebooks/rstudio
        - name: create-notebook-folders
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sh"]
          args: ["-c", "mkdir -p /data/notebooks/{{ name }}"]
          volumeMounts:
            - mountPath: /data
              name: persistentfsvol
        # This container sets the folder permissions for the generated notebook directory to be usable by
        # datalabs:users.
        - name: set-directory-permissions
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sh"]
          args: ["-c", "chmod 777 /data/notebooks && chmod 777 /data/notebooks/{{ name }}"]
          volumeMounts:
            - mountPath: /data
              name: persistentfsvol
        # This container will create the /home/datalabs to /data/notebooks/rstudio symlink
        - name: create-datalab-symlink
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "ln -s /data/notebooks/{{ name }}/ /home/datalab"]
          volumeMounts:
            - mountPath: /home
              name: homedir
      containers:
        - name: {{ name }}-connect
          image: {{ &rstudio.connectImage }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: CONNECT_TYPE
              value: RSTUDIO
          livenessProbe:
            httpGet:
              path: /status
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
        - name: {{ name }}
          image: {{ &rstudio.image }}
          imagePullPolicy : IfNotPresent
          ports:
            - containerPort: 8787
              protocol: TCP
          env:
            - name: USER
              value: datalab
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ name }}
                  key: password
            - name: ROOT
              value: 'TRUE'
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 2
              memory: 8Gi
          livenessProbe:
            httpGet:
              path: /
              port: 8787
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
{{#volumeMount}}
            - name: persistentfsvol
              mountPath: /data
            - name: homedir
              mountPath: /home
{{/volumeMount}}
            - name: rstudio-notebook-config
              mountPath: /etc/rstudio/rserver.conf
              subPath: rserver.conf
      volumes:
{{#volumeMount}}
        - name: persistentfsvol
          persistentVolumeClaim:
            claimName: {{ volumeMount }}-claim
        - name: homedir
          emptyDir: {}
{{/volumeMount}}
        - name: rstudio-notebook-config
          configMap:
            name: {{ rstudioConfigMapName }}
            items:
            - key: config
              path: rserver.conf
