---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ configMapName }}
data:
  config: |
    rsession-which-r=/usr/local/bin/R
    # www-root-path doesn't seem to work before R4.0.4, and doesn't seem to be necessary (yet)
    # www-root-path={{{ basePath }}}
