---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: {{ name }}
  name: {{ name }}
spec:
  selector:
    matchLabels:
      name: {{ name }}
  template:
    metadata:
      labels:
        name: {{ name }}
        user-pod: {{ type }}
    spec:
      # No init container need as the subPath variable only mounts the required directory. If the directory is missing
      # this is automatically created.
      containers:
        - name: {{ name }}
          image: {{ &image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8866
              protocol: TCP
          command: ["/bin/bash"]
          args: ["-c",
            "cd /notebooks;
            if [ -n \"$FILENAME\" ]; then
              voila $FILENAME;
            else 
              voila .;
            fi;"]
          env:
            - name: CONDA_ENV_DIR
              value: "/data/conda/"
            - name: JUPYTER_DATA_DIR
              value: "/data/.jupyter"
            - name: FILENAME
              value: {{ &serveFile }}
          livenessProbe:
            httpGet:
              path: /
              port: 8866
            initialDelaySeconds: 5
            periodSeconds: 10
{{#volumeMount}}
          volumeMounts:
            - name: persistentfsvol
              mountPath: /notebooks
              subPath: {{ &sourcePath }}
              readOnly: true
            - name: persistentfsvol
              mountPath: /data/conda
              subPath: conda
              readOnly: true
            - name: persistentfsvol
              mountPath: /data/.jupyter
              subPath: .jupyter
              readOnly: false
      volumes:
        - name: persistentfsvol
          persistentVolumeClaim:
            claimName: {{ volumeMount }}-claim
{{/volumeMount}}
