---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: {{ name }}
  name: {{ name }}
spec:
  selector:
    matchLabels:
      name: {{ name }}
  template:
    metadata:
      labels:
        name: {{ name }}
        user-pod: {{ type }}
    spec:
      securityContext:
        runAsUser: 1000
      serviceAccountName: {{ serviceAccount }}
      initContainers:
        # This container will generate the expected folder structure, which has a workspace folder for vscode and conda folder for conda.
        # As the container runs a root these directories are owned by root and can
        # not be written to by datalabs:users (user:group; 1000:100).
        - name: create-notebook-folders
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["bash"]
          args: ["-c", "mkdir -p /mnt/persistentfs/notebooks/{{ name }}/{workspace,conda} /mnt/persistentfs/notebooks/{{ name }}/.vscode/{extensions,data}"]
          volumeMounts:
            - mountPath: /mnt/persistentfs
              name: persistentfsvol
        # This container sets the folder permissions for the generated workspace and conda directories to be usable by
        # datalabs:users.
        - name: set-directory-permissions
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["bash"]
          args: ["-c", "chmod 777 /mnt/persistentfs/notebooks/{{ name }} /mnt/persistentfs/notebooks/{{ name }}/workspace /mnt/persistentfs/notebooks/{{ name }}/conda && ln -sfn /assets /mnt/persistentfs/notebooks/{{ name }}/assets"]
          volumeMounts:
            - mountPath: /mnt/persistentfs
              name: persistentfsvol
      containers:
        - image: {{ &vscode.image }}
          imagePullPolicy : "IfNotPresent"
          name: {{ name }}
          command: ["/bin/sh",
            "-c",
            "exec /home/.openvscode-server/bin/openvscode-server --host 0.0.0.0 --connection-token $(ACCESS_TOKEN) --user-data-dir /data/notebooks/{{ name }}/.vscode/data  --extensions-dir
          /data/notebooks/{{ name }}/.vscode/extensions"
          ]
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ name }}
                  key: token
            - name: GRANT_SUDO
              value: "{{ grantSudo }}"
            - name: CONDA_ENV_DIR
              value: "/data/conda/"
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 2
              memory: 8Gi
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 5
          volumeMounts:
            {{#volumeMount}}
            - name: persistentfsvol
              mountPath: /data
            {{/volumeMount}}
      volumes:
        {{#volumeMount}}
        - name: persistentfsvol
          persistentVolumeClaim:
            claimName: {{ volumeMount }}-claim
        {{/volumeMount}}
