test_namespace:
  name: test
  datalabName: testlab
  internalVolumeSize: 10G
  minio:
    accessKey: "{{ test_minio_shared_store_access_key }}"
    secretKey: "{{ test_minio_shared_store_secret_key }}"
  domain: test-datalabs.nerc.ac.uk
  nginxVersion: 0.9.0-beta.15
  ports:
    httpNodePort: "{{ test_ingress_http_port }}"
    httpsNodePort: "{{ test_ingress_https_port }}"
  defaultBackend:
    version: 0.2.0
    policy: localhost/docker-default
prod_namespace:
  name: prod
  datalabName: datalab
  internalVolumeSize: 10G
  minio:
    accessKey: "{{ minio_shared_store_access_key }}"
    secretKey: "{{ minio_shared_store_secret_key }}"
  domain: datalabs.nerc.ac.uk
  nginxVersion: 0.9.0-beta.15
  ports:
    httpNodePort: "{{ prod_ingress_http_port }}"
    httpsNodePort: "{{ prod_ingress_https_port }}"
  defaultBackend:
    version: 0.2.0
    policy: localhost/docker-node-alpine
