---

- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Join to Kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm join --token {{ kube_join_token }} \
                --discovery-token-unsafe-skip-ca-verification \
                {{ kube_master_ip }}:6443
  register: join_cluster
  notify:
    - Recreate kube-dns
