# traefik.toml
logLevel = "DEBUG"
accessLogsFile = "/logs/access.log"
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"

[web]
address = ":8080"

[file]

# rules
[backends]
  [backends.files]
    [backends.files.servers.server1]
    url = "http://minio:9000"
    weight = 1
  [backends.files-connect]
    [backends.files-connect.servers.server1]
    url = "http://minio-connect"
    weight = 1
  [backends.zeppelin]
    [backends.zeppelin.servers.server1]
    url = "http://zeppelin:8080"
    weight = 1
  [backends.zeppelin-connect]
    [backends.zeppelin-connect.servers.server1]
    url = "http://zeppelin-connect:8000"
    weight = 1
  [backends.jupyter]
      [backends.jupyter.servers.server1]
      url = "http://jupyter:8888"
      weight = 1

[frontends]
  [frontends.files]
  backend = "files"
    [frontends.files.routes.test_1]
    rule = "Host:testlab-files.datalabs.local"
  [frontends.files-connect]
  backend = "files-connect"
    [frontends.files-connect.routes.test_1]
    rule = "Host:testlab-files.datalabs.local;Path:/connect/;PathStrip:/connect/"
  [frontends.zeppelin]
  backend = "zeppelin"
    [frontends.zeppelin.routes.test_1]
    rule = "Host:testlab-zeppelin.datalabs.local"
  [frontends.zeppelin-connect]
  backend = "zeppelin-connect"
    [frontends.zeppelin-connect.routes.test_1]
    rule = "Host:testlab-zeppelin.datalabs.local;Path:/connect/;PathStrip:/connect/"
  [frontends.jupyter]
    backend = "jupyter"
      [frontends.jupyter.routes.test_1]
      rule = "Host:testlab-jupyter.datalabs.local"
