---
# Vagrant is able to provision Ansible into a new VM but requires a playbook
# to be supplied as a parameter.
# Given we don't actually want to provision any software into the control
# VM at the current time we aer just supplying an emtpy playbook
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Generate en_GB locale
      locale_gen:
        name: en_GB.UTF-8
        state: present

    - name: Install build-essential
      apt:
        name: build-essential
        state: present

    - name: Install libffi-dev
      apt:
        name: libffi-dev
        state: present

    - name: Install libssl-dev
      apt:
        name: libssl-dev
        state: present

    - name: Install libxml2-dev
      apt:
        name: libxml2-dev
        state: present

    - name: Install libxslt-dev
      apt:
        name: libxslt-dev
        state: present

    - name: Install python-dev
      apt:
        name: python-dev
        state: present

    - name: Install python-pip
      apt:
        name: python-pip
        state: present

    - name: Install pyvcloud
      pip: name=pyvcloud

    - name: Install vca-cli
      pip: name=vca-cli

    - name: Install xmltodict
      pip: name=xmltodict

    - name: Install jmespath
      pip: name=jmespath

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Install vcd-cli
      pip:
        name: vcd-cli
        executable: pip3
