# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.forward_agent = true

  config.vm.define "control" do |control|
    control.vm.box = "ubuntu/xenial64"
    control.vm.hostname = "datalab-control"
    control.vm.network "private_network", ip: "192.168.33.2"
    control.vm.synced_folder "~/.config/openstack", "/home/vagrant/.config/openstack"
    control.vm.synced_folder "playbooks", "/home/vagrant/playbooks"
    control.vm.synced_folder "infrastructure", "/home/vagrant/infrastructure"
    control.vm.synced_folder "rke", "/home/vagrant/rke"
    control.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
    end

    control.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.install_mode = "pip"
      ansible.version = "2.9.5"
      #ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
    end
  end
end
