---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-claim
  namespace: devtest
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
