---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scratch-claim
  namespace: test
  annotations:
    volume.beta.kubernetes.io/storage-class: glusterfs-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5G
