---
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Install ca-certificates
  apt:
    name: ca-certificates
    state: present

- name: Install curl
  apt:
    name: curl
    state: present

- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: present

- apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    state: present

- apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Update repositories cache and install docker
  apt:
    name: docker-ce
    update_cache: yes

- name: Download docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.12.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: ugo+x

- name: Create Docker group
  group:
    name: docker
    state: present

- name: Add docker user to docker group
  user:
    name: deploy
    group: docker

- name: Ensure docker service is running and enabled
  service:
    name: docker
    state: started
    enabled: yes
