---
# Install pre requisites for Docker installation
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Install ca-certificates
  apt:
    name: ca-certificates
    state: present

- name: Install curl
  apt:
    name: curl
    state: present

- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: present

# Prepare alternative docker location
- name: Update docker configuration if storage location set
  include_tasks: update-docker-config.yml
  when: docker_storage_location and docker_storage_location != ''

# Install docker
- apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    id: "{{ docker_apt_key }}"
    state: present

- apt_repository:
    repo: "{{docker_repository}}"
    state: present

- name: Update repositories cache and install docker
  apt:
    name: "docker.io={{ docker_version }}"
    update_cache: yes

# Docker post installation steps
- name: Create Docker group
  group:
    name: docker
    state: present

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    group: docker

- name: Ensure docker service is running and enabled
  service:
    name: docker
    state: started
    enabled: yes

# Install docker-compose to allow management of groups of containers
- name: Download docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: ugo+x

# docker-py is required on the host to allow ansible to manage containers
- name: Install python-pip
  apt:
    name: python3-pip
    state: present

- name: Install docker-py
  pip:
    name: docker-py
