version: '3'
services:
  mongodb:
    image: mongo:3.5
    ports:
      - 27017:27017

  mongodb_import:
    build:
      context: $PWD/../config/mongo
      dockerfile: mongo-import.Dockerfile
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB_NAME=datalab
    depends_on:
      - mongodb
    volumes:
      - $PWD/../config/mongo:/tmp/mongodb/:ro
