version: '3.7'

services:
  minikube-proxy-secure:
    build:
      context: ${PWD}/docker
      dockerfile: ${PWD}/docker/socat-proxy.dockerfile
    image: socat-proxy
    environment:
      SERVER_IP: 192.168.99.100
      SERVER_PORT: 80
    ports:
      - 80:80

  minikube-proxy-insecure:
    build:
      context: ${PWD}/docker
      dockerfile: ${PWD}/docker/socat-proxy.dockerfile
    image: socat-proxy
    environment:
      SERVER_IP: 192.168.99.100
      SERVER_PORT: 443
    ports:
      - 443:443
