version: '3.7'

x-common-variables: &common
  AUTHORISATION_SERVICE: http://datalab-auth:9000
  AUTH_SIGNIN_URL: http://datalabs.localhost
  DATABASE_HOST: mongodb
  INFRASTRUCTURE_API: http://datalab-infra:8003
  KUBERNETES_API: http://host.docker.internal:8001
  LOG_LEVEL: ${LOG_LEVEL:-info}
  VAULT_API: http://vault:8200
  VAULT_APP_ROLE: ${VAULT_APP_ROLE}

services:
  datalab-auth:
    image: node:8
    working_dir: /usr/src/app
    command: ["sh", "-c", "yarn start"]
    environment:
      <<: *common
      AUTHORISATION_API_CLIENT_ID: ${AUTHORISATION_API_CLIENT_ID}
      AUTHORISATION_API_CLIENT_SECRET: ${AUTHORISATION_API_CLIENT_SECRET}
      AUTHORISATION_API_IDENTIFIER: ${AUTHORISATION_API_IDENTIFIER}
      USER_MANAGEMENT_API_CLIENT_ID: ${USER_MANAGEMENT_API_CLIENT_ID}
      USER_MANAGEMENT_API_CLIENT_SECRET: ${USER_MANAGEMENT_API_CLIENT_SECRET}
      BABEL_DISABLE_CACHE: 1
    ports:
      - 9000:9000
    volumes:
      - ${PWD}/../auth-service:/usr/src/app/:ro

  datalab-infra:
    image: node:8
    working_dir: /usr/src/app
    command: ["sh", "-c", "yarn start"]
    environment:
      <<: *common
      BABEL_DISABLE_CACHE: 1
    ports:
      - 8003:8003
    volumes:
      - $PWD/../infrastructure-api:/usr/src/app/:ro
    links:
      - datalab-auth
      - mongodb
      - vault

  datalab-api:
    image: node:8
    working_dir: /usr/src/app/workspaces/client-api
    command: ["sh", "-c", "yarn start"]
    environment:
      <<: *common
      BABEL_DISABLE_CACHE: 1
    ports:
      - 8000:8000
    volumes:
      - $PWD/..:/usr/src/app:ro
    links:
      - datalab-auth
      - datalab-infra
      - mongodb
      - vault

  datalab-app:
    image: node:8
    working_dir: /usr/src/app/workspaces/web-app
    command: ["sh", "-c", "yarn start"]
    environment:
      BABEL_DISABLE_CACHE: 1
    ports:
      - 3000:3000
    volumes:
      - $PWD/..:/usr/src/app:ro
      # web_auth_config is unique to each domain and needs updating
      - $PWD/config/local/web_auth_config.json:/usr/src/app/workspaces/web-app/public/web_auth_config.json:ro

