version: '3.7'

services:
  mongodb:
    image: mongo:4.1.13-bionic
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=datalabs-root-u
      - MONGO_INITDB_ROOT_PASSWORD=datalabs-root-p
