version: '3'
services:
  datalab-auth:
    image: node:8
    environment:
      - AUTHORISATION_API_CLIENT_ID
      - AUTHORISATION_API_CLIENT_SECRET
      - AUTHORISATION_API_IDENTIFIER
      - LOG_LEVEL
    ports:
      - 9000:9000
    entrypoint: sh -c
    command:
      - cd /usr/src/app && yarn start
    network_mode: host
    volumes:
      - $PWD/../../auth-service:/usr/src/app/:ro

  datalab-infra:
    image: vault-role-wrapper
    environment:
      - LOG_LEVEL
    ports:
      - 8003:8003
    depends_on:
      - datalab-auth
      # - vault
    command:
      - cd /usr/src/app && yarn start
    network_mode: host
    volumes:
      - $PWD/../../infrastructure-api:/usr/src/app/:ro

  datalab-app-api:
    image: vault-role-wrapper
    environment:
      - LOG_LEVEL
    ports:
      - 3000:3000
      - 8000:8000
    depends_on:
      - datalab-auth
      # - mongodb
      # - vault
    command:
      - cd /usr/src/app && yarn start
    network_mode: host
    volumes:
      - $PWD/../../datalab-app:/usr/src/app:ro
