version: '3'
services:
  vault:
    image: vault:0.7.3
    ports:
      - 8200:8200
    command:
      - server
      - -dev
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
