version: "3.7"

x-common-variables: &common
  AUTHORISATION_SERVICE: http://datalab-auth:9000
  AUTH_SIGNIN_URL: http://datalabs.localhost
  AUTHORISATION_SERVICE_FOR_INGRESS: http://10.0.2.2:9000
  DATABASE_HOST: mongodb
  INFRASTRUCTURE_API: http://datalab-infra:8003
  KUBERNETES_API: http://host.docker.internal:8001
  LOG_LEVEL: ${LOG_LEVEL:-info}
  VAULT_API: http://vault:8200
  VAULT_APP_ROLE: ${VAULT_APP_ROLE}
  NODE_OPTIONS: "--max-http-header-size=81920"
  DEPLOYED_IN_CLUSTER: "false"
  NODE_EXTRA_CA_CERTS: /usr/src/rootCA.pem

services:
  datalab-auth:
    image: node:lts
    working_dir: /usr/src/app/workspaces/auth-service
    command: ["sh", "-c", "yarn start"]
    environment:
      <<: *common
      AUTHORISATION_API_IDENTIFIER: ${AUTHORISATION_API_IDENTIFIER}
      # Keycloak Authentication Parameters
      # OIDC_OAUTH_TOKEN_ENDPOINT: "/protocol/openid-connect/token"
      # OIDC_JWKS_ENDPOINT: "/protocol/openid-connect/certs"
      # OIDC_PROVIDER_DOMAIN: "keycloak:8080/auth/realms/DataLabs"
      # OIDC_PROVIDER_AUDIENCE: "account"
      BABEL_DISABLE_CACHE: 1
    ports:
      - 9000:9000
    volumes:
      - ${PWD}/..:/usr/src/app/:ro
      - ${PWD}/config/ca/rootCA.pem:/usr/src/rootCA.pem

  datalab-infra:
    image: node:lts
    working_dir: /usr/src/app/workspaces/infrastructure-api
    command: ["sh", "-c", "yarn start"]
    environment:
      <<: *common
      BABEL_DISABLE_CACHE: 1
    ports:
      - 8003:8003
    volumes:
      - $PWD/..:/usr/src/app/:ro
      - $PWD/config/local/image_config.json:/usr/src/app/workspaces/common/src/config/image_config.json:ro
      - $PWD/config/local/storage_config.json:/usr/src/app/workspaces/common/src/config/storage_config.json:ro
      - ${PWD}/config/ca/rootCA.pem:/usr/src/rootCA.pem

  datalab-api:
    image: node:lts
    working_dir: /usr/src/app/workspaces/client-api
    command: ["sh", "-c", "yarn start"]
    environment:
      <<: *common
      BABEL_DISABLE_CACHE: 1
    ports:
      - 8000:8000
    volumes:
      - $PWD/..:/usr/src/app:ro
      - $PWD/config/local/storage_config.json:/usr/src/app/workspaces/common/src/config/storage_config.json:ro
      - ${PWD}/config/ca/rootCA.pem:/usr/src/rootCA.pem

  datalab-app:
    image: node:lts
    working_dir: /usr/src/app/workspaces/web-app
    command: ["sh", "-c", "yarn start"]
    environment:
      BABEL_DISABLE_CACHE: 1
    ports:
      - 3000:3000
    volumes:
      - $PWD/..:/usr/src/app:ro
      - $PWD/config/local/storage_config.json:/usr/src/app/workspaces/web-app/public/storage_config.json:ro
      - $PWD/config/local/image_config.json:/usr/src/app/workspaces/web-app/public/image_config.json:ro
      - $PWD/config/local/catalogue_config.json:/usr/src/app/workspaces/web-app/public/catalogue_config.json:ro
      # web_auth_config is unique to each domain
      # When using KeyCloak unhash the line below and hash the Auth0 line
      # - $PWD/config/local/web_auth_config_keycloak.json:/usr/src/app/workspaces/web-app/public/web_auth_config.json:ro
      # When using Auth0 unhash the line below and hash the Keycloak line
      - $PWD/config/local/web_auth_config.json:/usr/src/app/workspaces/web-app/public/web_auth_config.json:ro
      - ${PWD}/config/ca/rootCA.pem:/usr/src/rootCA.pem
