version: '3'
services:
  vault:
    image: vault:1.0.3
    ports:
      - 8200:8200
    command:
      - server
      - -dev-kv-v1
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
