version: '3.7'

x-common-variables: &common
  AUTHORISATION_SERVICE: http://datalab-auth:9000
  DATABASE_HOST: mongodb
  INFRASTRUCTURE_API: http://datalab-infra:8003
  KUBERNETES_API: http://host.docker.internal:8001
  LOG_LEVEL: ${LOG_LEVEL:-info}
  VAULT_API: vault
  VAULT_APP_ROLE: ${VAULT_APP_ROLE}

services:
  datalab-auth:
    image: node:8
    working_dir: /usr/src/app
    command: ["sh", "-c", "yarn start"]
    environment:
      <<: *common
      AUTHORISATION_API_CLIENT_ID: ${AUTHORISATION_API_CLIENT_ID}
      AUTHORISATION_API_CLIENT_SECRET: ${AUTHORISATION_API_CLIENT_SECRET}
      AUTHORISATION_API_IDENTIFIER: ${AUTHORISATION_API_IDENTIFIER}
      USER_MANAGEMENT_API_CLIENT_ID: ${USER_MANAGEMENT_API_CLIENT_ID}
      USER_MANAGEMENT_API_CLIENT_SECRET: ${USER_MANAGEMENT_API_CLIENT_SECRET}
    ports:
      - 9000:9000
    volumes:
      - ${PWD}/../../auth-service:/usr/src/app/:ro
    networks:
      - internal

  datalab-infra:
    image: node:8
    working_dir: /usr/src/app
    command: ["sh", "-c", "yarn start"]
    environment:
      <<: *common
    ports:
      - 8003:8003
    volumes:
      - $PWD/../../infrastructure-api:/usr/src/app/:ro
    networks:
      - internal
    links:
      - datalab-auth
      - mongodb

  datalab-api:
    image: node:8
    working_dir: /usr/src/app
    command: ["sh", "-c", "yarn api"]
    environment:
      <<: *common
    ports:
      - 8000:8000
    volumes:
      - $PWD/../../datalab-app:/usr/src/app:ro
    networks:
      - internal
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:datalabs-api.localhost
      - traefik.docker.network=docker_internal
      - traefik.port=8000
    links:
      - datalab-auth
      - datalab-infra
      - mongodb

  datalab-app:
    image: node:8
    working_dir: /usr/src/app
    command: ["sh", "-c", "yarn app"]
    ports:
      - 3000:3000
    volumes:
      - $PWD/../../datalab-app:/usr/src/app:ro
    networks:
      - internal
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:datalabs.localhost
      - traefik.docker.network=docker_internal
      - traefik.port=3000

  traefik:
    image: traefik
    ports:
      - 80:80
      - 8080:8080
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/../config/traefik/traefik.toml:/traefik.toml

networks:
  internal:
    ipam:
      config:
        - subnet: 172.16.60.0/24
