version: '3'
services:
  datalab-infra:
    environment:
      - VAULT_APP_ROLE
      - LOG_LEVEL
      - AUTHORISATION_SERVICE=http://datalab-auth:9000
      - DATABASE_HOST=docker.for.mac.localhost
      - KUBERNETES_API=http://docker.for.mac.localhost:8001
      - VAULT_API=http://docker.for.mac.localhost:8200
    links:
      - datalab-auth

  datalab-app-api:
    environment:
      - VAULT_APP_ROLE
      - LOG_LEVEL
      - AUTHORISATION_SERVICE=http://datalab-auth:9000
      - INFRASTRUCTURE_API=http://datalab-infra:8003
      - DATABASE_HOST=docker.for.mac.localhost
      - VAULT_API=http://docker.for.mac.localhost:8200
    links:
      - datalab-auth
      - datalab-infra
