version: '3'
services:
  mongodb:
    image: mongo:3.4
    ports:
      - 27017:27017

  mongodb_import:
    image: mongo:3.4
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATALAB_DB_NAME=datalab
      - MONGO_INFRASTRUCTURE_DB_NAME=infrastructure
    depends_on:
      - mongodb
    command: bash -c "cp /tmp/mongodb/import.sh /usr/local/bin && chmod +x /usr/local/bin/import.sh && import.sh"
    volumes:
      - $PWD/../config/mongo:/tmp/mongodb/:ro
