---
- name: Setup ufw
  ufw:
    state: enabled
    policy: deny

- name: Allow ssh traffic from machines allowed to manage this node
  ufw:
    rule: allow
    port: "{{ ssh_port }}"
    from_ip: "{{ item }}"
    proto: tcp
  with_items: "{{ management_ip_addresses }}"

- name: Add cluster IPs on correct interface to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ item.internal_ip }} {{ item.name }}"
    insertbefore: BOF
    regexp: "{{ item.name }}$"
  with_items: "{{ private_servers }}"
