export const MODAL_TYPE_CREATE_NOTEBOOK = 'MODAL_TYPE_CREATE_NOTEBOOK';
export const MODAL_TYPE_CREATE_SITE = 'MODAL_TYPE_CREATE_SITE';
export const MODAL_TYPE_CONFIRMATION = 'MODAL_TYPE_CONFIRMATION';
