export const MODAL_TYPE_CREATE_NOTEBOOK = 'MODAL_TYPE_CREATE_NOTEBOOK';
export const MODAL_TYPE_CREATE_SITE = 'MODAL_TYPE_CREATE_SITE';
export const MODAL_TYPE_CONFIRMATION = 'MODAL_TYPE_CONFIRMATION';
export const MODAL_TYPE_CREATE_DATA_STORE = 'MODAL_TYPE_CREATE_STORE';
export const MODAL_TYPE_ROBUST_CONFIRMATION = 'MODAL_TYPE_ROBUST_CONFIRMATION';
