version: '3'
services:
  nginx:
    image: nginx:1.13.3
    ports:
    - 80:80
    - 443:443
    volumes:
    - /etc/ssl/private/datalabskey.pem:/etc/ssl/private/datalabskey.pem
    - /etc/ssl/certs/datalabs.pem:/etc/ssl/certs/datalabs.pem
    - ${PWD}/datalab.conf:/etc/nginx/conf.d/datalab.conf
