version: '3'
services:
  proxy:
    image: 'traefik'
    ports:
      - '8081:8080'
      - '80:80'
    volumes:
      - ${PWD}/config/traefik/traefik.toml:/etc/traefik/traefik.toml

  mongodb:
    image: mongo:3.4
    ports:
      - 27017:27017

  mongodb_import:
    build:
      context: ./config/mongo
      dockerfile: Dockerfile.mongoimport
    command: "/import.sh"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB_NAME=datalab
    depends_on:
      - mongodb
    volumes:
      - $PWD/config/mongo:/tmp/mongodb/:ro

  vault:
    image: 'vault'
    ports:
      - 8200:8200
    command:
      - server
      - -dev
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root

  minio:
    image: minio/minio
    ports:
      - 9000:9000
    volumes:
      - /tmp/minio/data:/export
    command:
      - server
      - /export
    environment:
      MINIO_ACCESS_KEY: VXL8C2ITGFBVMHKV2EV6
      MINIO_SECRET_KEY: iUOhbVYNRxJS2X+5Ukpvsk01TsVWxbdERaNGf5kI

  zeppelin:
    image: nerc/zeppelin:0.7.2
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/config/zeppelin/shiro.ini:/opt/zeppelin/conf/shiro.ini

  jupyter:
    image: jupyter/base-notebook:b4dd11e16ae4
    ports:
      - 8888:8888
    command:
      - start-notebook.sh
      - --NotebookApp.token=jupyterToken

  minio-connect:
    image: nerc/connect:latest
    ports:
      - 9001:80
    environment:
      ORIGIN: localhost:3000
      ACTIONS: "['set']"

  zeppelin-connect:
    image: nerc/zeppelin-connect
    ports:
      - 8083:8000
