version: '3'
services:
  vault:
    image: 'vault'
    ports:
      - '8200:8200'
    command:
      - server
      - -dev
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - /tmp/minio/data:/export
    command:
      - server
      - /export
    environment:
      MINIO_ACCESS_KEY: VXL8C2ITGFBVMHKV2EV6
      MINIO_SECRET_KEY: iUOhbVYNRxJS2X+5Ukpvsk01TsVWxbdERaNGf5kI