version: '3'
services:
  proxy:
    image: 'traefik'
    ports:
      - '8081:8080'
      - '80:80'
    volumes:
      - ${PWD}/config/traefik/traefik.toml:/etc/traefik/traefik.toml

  vault:
    image: 'vault'
    ports:
      - 8200:8200
    command:
      - server
      - -dev
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root

  minio:
    image: minio/minio
    ports:
      - 9000:9000
    volumes:
      - /tmp/minio/data:/export
    command:
      - server
      - /export
    environment:
      MINIO_ACCESS_KEY: VXL8C2ITGFBVMHKV2EV6
      MINIO_SECRET_KEY: iUOhbVYNRxJS2X+5Ukpvsk01TsVWxbdERaNGf5kI

  minio-connect:
    image: nerc/connect:latest
    ports:
      - 9001:80
    environment:
      ORIGIN: minio.docker.localhost
      ACTIONS: "['set']"

  zeppelin:
    image: nerc/zeppelin:0.7.2
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/config/zeppelin/shiro.ini:/opt/zeppelin/conf/shiro.ini
