- hosts: datalabs-terraform-state
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
    - install-python

- hosts: datalabs-terraform-state
  become: yes
  become_method: sudo
  roles:
    - reset-machine-id
    - base-configuration

  tasks:
    - name: Setup ufw
      ufw:
        state: enabled
        policy: deny

    - name: Add hostname to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        line: "127.0.0.1 datalabs-terraform-state"
        insertbefore: BOF
        regexp: "datalabs-terraform-state$"

    - name: Rescan drives
      command: bash -c "for BUS in /sys/class/scsi_host/host*/scan; do echo '- - -' >> $BUS; done"

#    - name: Format the disk
#      filesystem:
#        fstype: ext4
#        dev: "/dev/sdb"

    - name: Create the mount points for the disks
      file:
        path: "/data"
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        state: directory

    - name: Mount device
      mount:
        path: "/data"
        src: "/dev/sdb"
        fstype: ext4
        state: mounted
