ansible_python_interpreter: /usr/bin/python3

ssh_port: 22
bastion_ip_address: 192.171.139.117
bastion_internal_ip_address: 192.168.3.2
deploy_user: deploy
ansible_sudo_pass: "{{ vault_deploy_password }}" # Note that this is the uncrypted version of the deploy user password

root_password_crypted: "{{ vault_root_password_crypted }}"
deploy_password_crypted: "{{ vault_deploy_password_crypted }}"

logwatch_email: "gareth.lloyd@stfc.ac.uk"
slack_token: "{{ vault_slack_token }}"

deploy_public_keys:
  - gary_rsa.pub
  - josh_rsa.pub

base_packages:
  - aptitude
  - ufw
  - fail2ban
  - unattended-upgrades
  - logwatch