ansible_python_interpreter: /usr/bin/python3

datalabs_domain: datalabs.ceh.ac.uk
dynamic_proxy_api: "http://{{ external_proxy_internal_ip_address }}:8081"

ssh_port: 22
bastion_ip_address: 192.171.139.245
bastion_internal_ip_address: 192.168.3.41
external_proxy_internal_ip_address: 192.168.3.35
#test_proxy_internal_ip_address: 192.168.3.30
deploy_user: ubuntu
#ansible_sudo_pass: "{{ vault_deploy_password }}" # Note that this is the uncrypted version of the deploy user password

#root_password_crypted: "{{ vault_root_password_crypted }}"
#deploy_password_crypted: "{{ vault_deploy_password_crypted }}"

#slack_token: "{{ vault_slack_token }}"

#heketi_ssh_password: "{{ vault_heketi_ssh_password }}"

k8s_api_port: 6443
test_ingress_http_port: 31080
test_ingress_https_port: 31443
prod_ingress_http_port: 30080
prod_ingress_https_port: 30443

sendgrid_api_key: "{{ vault_sendgrid_api_key }}"
