---
- name: Deploy Test TLS Secrets
  shell: kubectl create secret generic tls-secret --from-literal=tls.crt="{{ test_ssl_certificate }}" --from-literal=tls.key="{{ test_ssl_private_key }}" --type=kubernetes.io/tls -n test
  register: test_tls_secret_result
  changed_when: test_tls_secret_result.rc == 0
  failed_when: test_tls_secret_result.rc != 0 and 'AlreadyExists' not in test_tls_secret_result.stderr

- name: Deploy Prod TLS Secrets
  shell: kubectl create secret generic tls-secret --from-literal=tls.crt="{{ ssl_certificate }}" --from-literal=tls.key="{{ ssl_private_key }}" --type=kubernetes.io/tls -n prod
  register: prod_tls_secret_result
  changed_when: prod_tls_secret_result.rc == 0
  failed_when: prod_tls_secret_result.rc != 0 and 'AlreadyExists' not in prod_tls_secret_result.stderr

- name: Deploy Test Auth Signing Keys
  shell: kubectl create secret generic auth-signing-key --from-literal=public="{{ test_authorisation_public_key }}" --from-literal=private="{{ test_authorisation_private_key }}" -n test
  register: test_auth_secret_result
  changed_when: test_auth_secret_result.rc == 0
  failed_when: test_auth_secret_result.rc != 0 and 'AlreadyExists' not in test_auth_secret_result.stderr

- name: Deploy Prod Auth Signing Keys
  shell: kubectl create secret generic auth-signing-key --from-literal=public="{{ authorisation_public_key }}" --from-literal=private="{{ authorisation_private_key }}" -n prod
  register: prod_auth_secret_result
  changed_when: prod_auth_secret_result.rc == 0
  failed_when: prod_auth_secret_result.rc != 0 and 'AlreadyExists' not in prod_auth_secret_result.stderr

- name: Deploy Test Authorisation API client secret
  shell: kubectl create secret generic authorisation-api-client-secret --from-literal=secret="{{ authorisation_api_client_secret }}" -n test
  register: test_authorisation_secret_result
  changed_when: test_authorisation_secret_result.rc == 0
  failed_when: test_authorisation_secret_result.rc != 0 and 'AlreadyExists' not in test_authorisation_secret_result.stderr

- name: Deploy Prod Authorisation API client secret
  shell: kubectl create secret generic authorisation-api-client-secret --from-literal=secret="{{ authorisation_api_client_secret }}" -n prod
  register: prod_authorisation_secret_result
  changed_when: prod_authorisation_secret_result.rc == 0
  failed_when: prod_authorisation_secret_result.rc != 0 and 'AlreadyExists' not in prod_authorisation_secret_result.stderr

- name: Deploy Test User Management API client secret
  shell: kubectl create secret generic user-management-api-client-secret --from-literal=secret="{{ user_management_api_client_secret }}" -n test
  register: test_user_management_api_client_secret
  changed_when: test_user_management_api_client_secret.rc == 0
  failed_when: test_user_management_api_client_secret.rc != 0 and 'AlreadyExists' not in test_user_management_api_client_secret.stderr

- name: Deploy Prod User Management API client secret
  shell: kubectl create secret generic user-management-api-client-secret --from-literal=secret="{{ user_management_api_client_secret }}" -n prod
  register: prod_authorisation_secret_result
  changed_when: prod_authorisation_secret_result.rc == 0
  failed_when: prod_authorisation_secret_result.rc != 0 and 'AlreadyExists' not in prod_authorisation_secret_result.stderr
