---
- name: Initialise Kubernetes control plane components
  command: kubeadm init --apiserver-advertise-address={{ k8s_master_ip }}
  args:
    creates: /etc/kubernetes/kubelet.conf
  register: kubeadm_init

- name: Copy kubectl config to deploy user home directory
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ deploy_user }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    remote_src: True

- name: Install WeaveNet pod network
  command: kubectl apply -f https://git.io/weave-kube-1.6

- name: Get kubeadm token
  shell: kubeadm token list | sed -n 2p | awk '{ print $1 };'
  register: kubeadm_token
  tags: always

- name: Set kubeadm_token fact for use in later playbooks run in the same context
  set_fact:
    kubeadm_token: "{{ kubeadm_token.stdout }}"
  tags: always

- name: Open firewall for API server access fom bastion
  ufw:
    rule: allow
    port: "{{ k8s_api_port }}"
    from_ip: "{{ bastion_internal_ip_address }}"
    proto: tcp

