apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: datalab-api-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: datalab-api
    spec:
      containers:
        - name: datalab-api
          image: nerc/datalab-api
          ports:
            - containerPort: 8000
