apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: docs-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
        - name: docs
          image: nerc/docs
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: docs-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: docs
  type: NodePort
