---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minio-connect-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minio-connect
    spec:
      containers:
        - name: minio-connect
          image: nerc/connect:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ORIGIN
              value: datalab.datalabs.nerc.ac.uk
            - name: ACTIONS
              value: "['set']"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: minio-connect-service
spec:
  ports:
    - name: minio-connect
      port: 80
      targetPort: 80
  selector:
    app: minio-connect
  type: NodePort
