apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9000
  selector:
    app: minio
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
  labels:
    app: minio
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minio-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          livenessProbe:
            httpGet:
              path: /minio
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
          - name: minio-persistent-storage
            mountPath: /export
          args: ["server", "/export"]
      volumes:
      - name: minio-persistent-storage
        persistentVolumeClaim:
          claimName: minio-pv-claim
