apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9000
  selector:
    app: minio
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minio-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          args: ["server", "/mnt/glusterfs"]
          volumeMounts:
            - mountPath: /mnt/glusterfs
              name: glusterfsvol
      volumes:
        - name: glusterfsvol
          glusterfs:
            endpoints: glusterfs-cluster
            path: datalab
            readOnly: false

