---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ name }}
  annotations:
    ingress.kubernetes.io/auth-url: {{ &authServiceUrl }}
    ingress.kubernetes.io/auth-signin: {{ &authSigninUrl }}
    ingress.kubernetes.io/proxy-body-size: {{ &maxBodySize }}
{{#rewriteTarget}}
    ingress.kubernetes.io/rewrite-target: {{ &rewriteTarget }}
{{/rewriteTarget}}
{{#proxyTimeout}}
    ingress.kubernetes.io/proxy-connect-timeout: "{{ &proxyTimeout }}"
    ingress.kubernetes.io/proxy-read-timeout: "{{ &proxyTimeout }}"
    ingress.kubernetes.io/proxy-send-timeout: "{{ &proxyTimeout }}"
    ingress.kubernetes.io/proxy-socket-keepalive: "on"
{{/proxyTimeout}}
spec:
  tls:
  - hosts:
    - {{ service.host }}
  rules:
  - host: {{ service.host }}
    http:
      paths:
{{#service.paths}}
      - path: {{ &path }}
        backend:
          serviceName: {{ serviceName }}
          servicePort: {{ servicePort }}
{{/service.paths}}
