---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ name }}
  labels:
    userCreated: "yes"
spec:
  storageClassName: {{ storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ volumeSize }}G
