---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ storageClass }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ volumeSize }}G