---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
      name: {{ name }}
  name: {{ name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ name }}
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "chown -R 1000:1000 /mnt/glusterfs"]
          volumeMounts:
            - mountPath: /mnt/glusterfs
              name: glusterfsvol
      containers:
        - name: minio
          image: {{ &minio.imageName }}:{{ minio.version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          env:
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ name }}
                key: access_key
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ name }}
                key: secret_key
          args: ["server", "/mnt/glusterfs"]
          volumeMounts:
            - mountPath: /mnt/glusterfs
              name: glusterfsvol
        - name: {{ name }}-connect
          image: {{ &minio.connectImageName }}:{{ minio.connectVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
          - name: ORIGIN
            value: {{ domain }}
          - name: ACTIONS
            value: "['set']"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: glusterfsvol
          persistentVolumeClaim:
            claimName: {{ volumeName }}-claim
