---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    name: {{ name }}
  name: {{ name }}
  namespace: {{ namespace }}
spec:
  template:
    metadata:
      labels:
        name: {{ name }}
    spec:
    spec:
      # No init container need as the subPath variable only mount the required directory. If the directory is miss this
      # is automatically created.
      containers:
      - name: {{ name }}
        image: {{ &nbviewer.imageName }}:{{ nbviewer.version }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        args: ["python3",
              "-m", "nbviewer",
              "--localfiles=/notebooks",
              "--debug",
              "--logging=debug",
              "--no-cache"]
{{#volumeMount}}
        volumeMounts:
        - name: glusterfsvol
          mountPath: /notebooks
          subPath: {{ &sourcePath }}
          readOnly: true
      volumes:
      - name: glusterfsvol
        persistentVolumeClaim:
          claimName: {{ volumeMount }}-claim
{{/volumeMount}}
