---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    name: {{ name }}
  name: {{ name }}
spec:
  template:
    metadata:
      labels:
        name: {{ name }}
        user-pod: {{ type }}
    spec:
      # No init container need as the subPath variable only mounts the required directory. If the directory is missing
      # this is automatically created.
      containers:
        - name: {{ name }}
          image: {{ &nbviewer.imageName }}:{{ nbviewer.version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              protocol: TCP
          args: ["python3",
                "-m", "nbviewer",
                "--localfiles=/notebooks",
                "--debug",
                "--logging=debug",
                "--no-cache"]
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
{{#volumeMount}}
          volumeMounts:
            - name: glusterfsvol
              mountPath: /notebooks
              subPath: {{ &sourcePath }}
              readOnly: true
      volumes:
        - name: glusterfsvol
          persistentVolumeClaim:
            claimName: {{ volumeMount }}-claim
{{/volumeMount}}
