---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    name: {{ name }}
  name: {{ name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ name }}
    spec:
      containers:
      - image: {{ &rshiny.imageName }}:{{ rshiny.version }}
        imagePullPolicy : "IfNotPresent"
        name:  {{ name }}
        ports:
        - containerPort: 3838
          protocol: TCP
        volumeMounts:
          - name: glusterfsvol
            mountPath: /srv/shiny-server
            subPath: {{ &sourcePath }}
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 1
            memory: 2Gi
      volumes:
        - name: glusterfsvol
          persistentVolumeClaim:
            claimName: {{ datalabVolume }}-claim
