---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    name: {{ name }}
  name: {{ name }}
  namespace: {{ namespace }}
spec:
  template:
    metadata:
      labels:
        name: {{ name }}
    spec:
      containers:
      - name: {{ name }}
        image: {{ &rstudio.imageName }}:{{ rstudio.version }}
        imagePullPolicy : IfNotPresent
        ports:
        - containerPort: 8787
          protocol: TCP
        env:
        - name: USER
          value: datalab
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ name }}
              key: password
        volumeMounts:
        - name: glusterfsvol
          mountPath: /data
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 2
            memory: 4Gi
      - name: {{ name }}-connect
        image: {{ &rstudio.connectImageName }}:{{ rstudio.connectVersion }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /status
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: glusterfsvol
        glusterfs:
          endpoints: glusterfs-cluster
          path: {{ datalabVolume }}
          readOnly: false
