---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    name: {{ name }}
  name: {{ name }}
  namespace: {{ namespace }}
spec:
  template:
    metadata:
      labels:
        name: {{ name }}
    spec:
      containers:
      - image: {{ &rstudio.imageName }}:{{ rstudio.version }}
        imagePullPolicy : "IfNotPresent"
        name: {{ name }}
        ports:
        - containerPort: 8787
          protocol: TCP
        volumeMounts:
        - name: glusterfsvol
          mountPath: /data
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 2
            memory: 4Gi
      volumes:
        - name: glusterfsvol
          glusterfs:
            endpoints: glusterfs-cluster
            path: {{ datalabVolume }}
            readOnly: false
