---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    name: {{ name }}
  name: {{ name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ name }}
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name:  {{ name }}
        image: {{ &zeppelin.imageName }}:{{ zeppelin.version }}
        imagePullPolicy : IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: MASTER
          value: {{ &sparkMasterAddress }}
        - name: SPARK_SUBMIT_OPTIONS
          value: "--packages com.esri.geometry:esri-geometry-api:1.2.1"
        - name: ZEPPELIN_JAVA_OPTS
          value: "-Dshell.command.timeout.millisecs=3600000"
        - name: ZEPPELIN_NOTEBOOK_DIR
          value: /data/notebooks/zeppelin
        - name: SECRET_CONFIG
          value: /secret/shiro.ini
        - name: GRANT_SUDO
          value: "{{ grantSudo }}"
        - name: R_LIBS_USER
          value: {{ &sharedRLibs }}
        volumeMounts:
          - name: glusterfsvol
            mountPath: /data
          - name: zeppelin-shiro
            mountPath: /secret
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 2
            memory: 4Gi
        livenessProbe:
          httpGet:
            path: index.html
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      - name: {{ name }}-connect
        image: {{ &zeppelin.connectImageName }}:{{ zeppelin.connectVersion }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
        - name: CONNECT_TYPE
          value: ZEPPELIN
        livenessProbe:
          httpGet:
            path: /status
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
        - name: glusterfsvol
          glusterfs:
            endpoints: glusterfs-cluster
            path: {{ datalabVolume }}
            readOnly: false
        - name: zeppelin-shiro
          secret:
            secretName: {{ name }}
