---
- name: Install Httpie
  apt:
    state: installed
    pkg: httpie
- name: Download dynamic-proxy compose file
  get_url:
    url: https://raw.githubusercontent.com/NERC-CEH/datalab/master/code/provision/kong-proxy/docker-compose.yml
    dest: /home/deploy/docker-compose.yml
    force: yes

- name: Download datalabs Kong nginx template file
  get_url:
    url: https://raw.githubusercontent.com/NERC-CEH/datalab/master/code/provision/kong-proxy/datalabs_nginx.template
    dest: /home/deploy/datalabs_nginx.template
    force: yes

- name: Open Firewall ports
  ufw:
    rule: allow
    port: "{{ item }}"
    from_ip: any
    proto: tcp
  with_items: "{{ proxy_ports }}"

- name: Ensure defined images in use
  shell: docker-compose pull

- name: Start dynamic-proxy
  shell: docker-compose up -d
