---
- name: Download dynamic-proxy compose file
  get_url:
    url: https://raw.githubusercontent.com/NERC-CEH/datalab/master/code/dynamic-proxy/docker-compose.yml
    dest: /home/deploy/docker-compose.yml

- name: Open Firewall ports
  ufw:
    rule: allow
    port: "{{ item }}"
    from_ip: any
    proto: tcp
  with_items: "{{ proxy_ports }}"

- name: Add IP Table rule to allow traffic on port 80
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination_port: 80
    jump: REDIRECT
    to_ports: 8080

- name: Start dynamic-proxy
  shell: docker-compose up -d

- name: Start documentation
  docker_container:
    name: docs
    image: nerc/docs
    ports:
      - "9000:80"

- name: Start managment application
  docker_container:
    name: datalab-app
    image: nerc/datalab-app
    ports:
      - "9001:80"
