apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: spark-worker
  name: spark-worker
spec:
  replicas: 4
  template:
    metadata:
      labels:
        name: spark-worker
    spec:
      containers:
      - image: nerc/spark:2.1.0.1
        imagePullPolicy : "IfNotPresent"
        name: spark-worker
        ports:
        - containerPort: 7078
          protocol: TCP
        env:
        - name: SPARK_ROLE
          value: WORKER
        volumeMounts:
            - mountPath: /data
              name: glusterfsvol
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 2
            memory: 4Gi
      volumes:
        - name: glusterfsvol
          glusterfs:
            endpoints: glusterfs-cluster
            path: datalab
            readOnly: false
