apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: spark-ui-proxy-controller
  name: spark-ui-proxy-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: spark-ui-proxy
    spec:
      containers:
      - name: spark-ui-proxy
        image: elsonrodriguez/spark-ui-proxy:1.0
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: 100m
        args:
          - spark-master:8080
        livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 120
            timeoutSeconds: 5
