name: PR Yarn Audit

on:
  pull_request:
    paths:
      - ".github/workflows/pr_api.yaml"
      - "build/**"
      - "code/yarn.lock"
      - "code/workspaces/common/**"
      - "code/workspaces/client-api/**"
      - "code/workspaces/infrastructure-api/**"
      - "code/workspaces/service-chassis/**"
      - "code/workspaces/auth-service/**"
      - "code/workspaces/web-app/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-cache-${{ env.CONTAINER }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-cache-${{ env.CONTAINER }}-
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Check vulnerabilities
        run: ./build/check-dependencies.sh
        shell: bash
