---
- name: Allow glusterfs TCPtraffic
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items: "{{ gluster_tcp_ports }}"

- name: Open ssh from kubernetes
  ufw:
    rule: allow
    from_ip: "{{ hostvars[item].openstack.private_v4 }}"
    port: 22
  with_items: "{{ groups['k8s-cluster'] }}"

- name: Allow glusterfs UDP traffic
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
  with_items: "{{ gluster_udp_ports }}"

- name: Add Signing key
  apt_key:
    url: "https://download.gluster.org/pub/gluster/glusterfs/{{ glusterfs_ppa_version }}/rsa.pub"
    state: present

- name: Add PPA for GlusterFS
  apt_repository:
    repo: 'ppa:gluster/glusterfs-{{ glusterfs_ppa_version }}'
    state: present
    update_cache: yes
  register: glusterfs_ppa_added

- name: Install dependencies
  apt:
    name: software-properties-common
    state: present

- name: Install Gluster dependency
  apt:
    name: thin-provisioning-tools
    state: present

- name: Ensure GlusterFS client is installed
  apt:
    name: glusterfs-client
    state: present

- name: Ensure GlusterFS server is installed if required
  apt:
    name: glusterfs-server
    state: present

- name: Ensure GlusterFS is started and enabled at boot
  systemd:
    name: glusterd
    state: started
    enabled: yes
